### ISSUE TITLE
run error 

### ISSUE THREAD

**Issue by xumh-9** [Tencent/ActionDetection-DBG#25]
Thanks for your work. But I met an error when I run this code:python pytorch/test.py config/config_pretrained.yaml .The error : 
Traceback (most recent call last):
  File "pytorch/test.py", line 11, in <module>
    from model import DBG
  File "/mnt/songyan/10519_xuminhuang/ActionDetection-DBG-master/pytorch/model.py", line 4, in <module>
    from custom_op.prop_tcfg_op import PropTcfg
  File "/mnt/songyan/10519_xuminhuang/ActionDetection-DBG-master/pytorch/custom_op/prop_tcfg_op.py", line 4, in <module>
    import prop_tcfg_cuda
ImportError: /mnt/songyan/10519_xuminhuang/anaconda3/lib/python3.7/site-packages/prop_tcfg_cuda-0.0.0-py3.7-linux-x86_64.egg/prop_tcfg_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd

my tool:
pytorch1.1
cuda9
python3.7
gcc5.4
Can someone help me solve this problem?thanks

**Comment by imtianyufu** [comment]
i have the same problem，Does anyone can help me how to sovle it

**Comment by lingyixia** [comment]
have you sove this problem? I meet it too
